services:
  bot:
    build: .
    container_name: schedule_bot
    restart: unless-stopped
    init: true
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 1.1.1.1