name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH and Git Pull
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home/app/andromedov/TNTU-Telegram-Schedule
          
          git fetch --all
          git reset --hard origin/main
          git pull origin main
          
          docker compose up -d --build
          
          docker image prune -f